Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)

In [12]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
print(a[1,2])   # Get the specific element

8


In [3]:
print(a[1,])    # Get specific Row

[ 6  7  8  9 10]


In [4]:
print(a[:,2])   # Get specific column

[3 8]


In [5]:
a[:,2] = [10,20]    # Changing elements
print(a)

[[ 1  2 10  4  5]
 [ 6  7 20  9 10]]


Initializing Different types of arrays

In [6]:
print(np.zeros((2,2)))  # All zeros matrice

[[0. 0.]
 [0. 0.]]


In [7]:
print(np.ones((2,3)))   # All ones matrice

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print(np.full((2,2), 88))   # Any other number

[[88 88]
 [88 88]]


In [9]:
print(np.full_like(a,99))   # Any other number (like the given array)

[[99 99 99 99 99]
 [99 99 99 99 99]]


In [10]:
print(np.random.randint(50,size=(2,3)))

[[23  9 45]
 [47 27 13]]


In [11]:
matrice = np.ones((5,5))
# print(matrice)

z = np.zeros((3,3))
z[1,1] = 9 
# print(z)

matrice[1:-1,1:-1] = z
print(matrice)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
